### ISSUE TITLE
Error from leva.core.SubPanel: "Invalid hook call. Hooks can only be called inside of the body of a function component."

### ISSUE THREAD

**Issue by matthewdowney** [mentat-collective/Leva.cljs#10]
Hi there,

I was just going through the examples, and everything works fine for me except the SubPanel component.

With the following code
```clojure
(ns core
  (:require [leva.core :as leva]
            [reagent.core :as r]
            [reagent.dom :as rdom]))

(defonce controls (r/atom {:width 500 :height 500}))

(defn app []
  [:div
   [leva/SubPanel {:fill true :titleBar {:drag false}}
    [leva/Controls {:folder {:name "Plot Controls"} :atom controls}]]])

;;; Lifecycle / entry point

(defn start [] (rdom/render [app] (.getElementById js/document "app")))
(defn stop [] (js/console.log "stopping..."))
(defn ^:export init [] (start))
```

I get this error in the JS console:

```
react-dom.development.js:16228 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

<details>
<summary>(Full stack trace)</summary>

```
react-dom.development.js:16228 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:16228:13)
    at exports.useMemo (react.development.js:1651:21)
    at exports.useCreateStore (leva.cjs.dev.js:1280:16)
    at Function.eval [as cljs$core$IFn$_invoke$arity$variadic] (core.cljs:156:16)
    at cmp.leva$core$SubPanel [as reagentRender] (core.cljs:139:1)
    at eval (component.cljs:88:28)
    at Object.reagent$impl$component$wrap_render [as wrap_render] (component.cljs:91:31)
    at Object.reagent$impl$component$do_render [as do_render] (component.cljs:117:6)
    at eval (component.cljs:260:64)
    at Object.reagent$ratom$in_context [as in_context] (ratom.cljs:44:6)
throwInvalidHookError @ react-dom.development.js:16228
exports.useMemo @ react.development.js:1651
exports.useCreateStore @ leva.cjs.dev.js:1280
eval @ core.cljs:156
leva$core$SubPanel @ core.cljs:139
eval @ component.cljs:88
reagent$impl$component$wrap_render @ component.cljs:91
reagent$impl$component$do_render @ component.cljs:117
eval @ component.cljs:260
reagent$ratom$in_context @ ratom.cljs:44
reagent$ratom$deref_capture @ ratom.cljs:57
reagent$ratom$run_in_reaction @ ratom.cljs:539
reagent$impl$component$wrap_funs_$_render @ component.cljs:260
finishClassComponent @ react-dom.development.js:19753
updateClassComponent @ react-dom.development.js:19699
beginWork @ react-dom.development.js:21612
callCallback @ react-dom.development.js:4165
invokeGuardedCallbackImpl @ react-dom.development.js:4214
invokeGuardedCallback @ react-dom.development.js:4278
beginWork$1 @ react-dom.development.js:27452
performUnitOfWork @ react-dom.development.js:26561
workLoopSync @ react-dom.development.js:26467
renderRootSync @ react-dom.development.js:26435
performSyncWorkOnRoot @ react-dom.development.js:26086
flushSyncCallbacks @ react-dom.development.js:12043
scheduleUpdateOnFiber @ react-dom.development.js:12022
updateContainer @ react-dom.development.js:28859
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29616
exports.render @ react-dom.development.js:29686
reagent$dom$render_comp @ dom.cljs:17
eval @ dom.cljs:51
eval @ dom.cljs:37
core$start @ VM3944 core.js:10
eval @ env.cljs:209
shadow$cljs$devtools$client$env$do_js_reload_STAR_ @ env.cljs:218
G__55374 @ env.cljs:218
eval @ env.cljs:247
shadow$cljs$devtools$client$env$do_js_reload_STAR_ @ env.cljs:218
G__55374 @ env.cljs:218
eval @ env.cljs:210
shadow$cljs$devtools$client$env$do_js_reload_STAR_ @ env.cljs:218
eval @ env.cljs:254
shadow$cljs$devtools$client$browser$do_js_reload @ browser.cljs:43
eval @ browser.cljs:93
eval @ shared.cljs:32
shadow$remote$runtime$shared$process @ shared.cljc:181
eval @ shared.cljs:289
shadow$cljs$devtools$client$shared$remote_msg @ shared.cljs:16
eval @ websocket.cljs:16
react-dom.development.js:18688 The above error occurred in the <leva.core.SubPanel> component:

    at leva.core.SubPanel (js/cljs-runtime/reagent.impl.component.js:499:43)
    at div
    at core.app (js/cljs-runtime/reagent.impl.component.js:499:43)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
</details>

After reading https://reactjs.org/link/invalid-hook-call, I think it's possibly something I am doing wrong here, but even in a slimmed down version of the project without other dependencies that might conflict, I run into the same thing.

I'm using shadow-cljs, and these are the contents of some of the key files:

<details>
<summary>package.json</summary>

```json
{
  "name": "leva-example",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "shadow-cljs": "2.22.2"
  },
  "dependencies": {
    "create-react-class": "^15.7.0",
    "leva": "0.9.34",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
```
</details>

<details>
<summary>shadow-cljs.edn</summary>

```clojure
; use deps.edn with the :shadow alias
{:deps {:aliases [:shadow]}
 :builds
 {:app
  {:target     :browser
   :output-dir "public/js"
   :asset-path "js"
   :modules    {:main {:entries [core]}}
   :devtools   {:preloads     [hashp.core]
                :repl-init-ns core
                :repl-pprint  true
                :before-load  core/stop
                :after-load   core/start
                :http-root    "public"
                :http-port    8020}}}}
```
</details>

<details>
<summary>deps.edn</summary>

```clojure
{:paths ["src"]
 :deps
 {org.clojure/clojure       {:mvn/version "1.11.1"}
  org.clojure/clojurescript {:mvn/version "1.11.60"}
  org.clojure/core.async    {:mvn/version "1.6.673"}
  reagent/reagent           {:mvn/version "1.2.0"
                             :exclusions  [cljsjs/react cljsjs/react-dom cljsjs/react-dom-server]}
  org.mentat/leva.cljs      {:mvn/version "0.2.2"}}

 :aliases
 {:shadow
  {:extra-deps
   {thheller/shadow-cljs {:mvn/version "2.21.0"}
    binaryage/devtools   {:mvn/version "1.0.5"}
    hashp/hashp          {:mvn/version "0.2.2"}}}}}
```
</details>

Have you run into anything like this?

**Comment by matthewdowney** [comment]
Thanks @sritchie! 

I created a minimal repro here: https://github.com/matthewdowney/leva-example

I was able to reproduce the issue by:

```
git clone https://github.com/matthewdowney/leva-example
cd leva-example
npm i
bb dev
```

And then browsing to the shadow-cljs HTTP server's port on localhost and opening the dev console.

**Comment by matthewdowney** [comment]
I got it to work, but my understanding of React / front end in general is at approximately the level of a golden retriever's, so apologies if this is incoherent. I think you'll be able to spot it right away.

As far as I can tell, `SubPanel` needs to be inside of `[:f> ...]` because it uses the `useCreateStore` hook. The obvious approach of 

```clojure
[:f> leva/SubPanel {:fill true :titleBar {:drag false}}
 [leva/Controls {:folder {:name "Plot Controls"} :atom controls}]]
```

runs into something about an `Uncaught TypeError: Cannot use 'in' operator to search for '[object Object]' in undefined` ... maybe related to creating a function component and passing children at the same time? 

So I Frankensteined some parts of Leva.cljs's core namespace, and that did it for me:

```clojure
(ns core
  (:require [leva :as l]
            ["react" :as react]
            [leva.schema :as schema]
            [reagent.core :as r]
            [reagent.dom :as rdom]))

(defonce controls (r/atom {:width 500 :height 500}))

(defn Config [opts & children]
  (if-let [store (:store opts)]
    [:<>
     [:> l/LevaPanel (assoc opts :store store)]
     (into [:> l/LevaStoreProvider {:store store}] children)]
    (into [:<> [:> l/Leva opts]] children)))

(defn SubPanel [opts & children]
  (let [store (l/useCreateStore)]
    (into [Config (assoc opts :store store)]
      children)))

(defn Controls* [opts]
  (let [[watch-id] (react/useState (str (random-uuid)))
        !state     (:atom opts)
        initial    (if !state (.-state !state) {})
        ks         (keys initial)
        opts       (update opts :store #(or % (l/useStoreContext)))
        [_ set] (apply l/useControls (schema/opts->argv opts))]
    (react/useEffect
      (fn mount []
        (if !state
          (do
            (add-watch !state watch-id
              (fn [_ _ _ new-state]
                (set (clj->js (select-keys new-state ks)))))
            (fn unmount []
              (remove-watch !state watch-id)))
          js/undefined)))
    nil))

(defn app []
  [:f> SubPanel {:fill true :titleBar {:drag false}}
   [:f> Controls* {:folder {:name "Plot Controls"} :atom controls}]])

;;; Lifecycle / entry point

(defn start [] (rdom/render [app] (.getElementById js/document "app")))
(defn ^:export init [] (start))
```

Is this hack just a longer way of doing some well-known but hard to Google React/Reagent thing to deal with this situation?

**Comment by sritchie** [comment]
Thank you for the lovely bug report!! This is all of the detail I've ever hoped for in an issue, though I rarely find that hope fulfilled.

I'm going to stare at this now and see if I can get it fixed up. I was surprised that the component wasn't working, since I thought that I had everything going well in the docs notebook, but you've indeed found a smoking gun with that hook usage.

More soon...

**Comment by sritchie** [comment]
Okay, #12 fixes this. I saw in your repro that backing Reagent off from 1.2.0 fixes it as well... I don't know why the lower version works, as this was a genuine bug from me. Thanks for tracking it down!

Give the latest git dependency a try:

```clj
{io.github.mentat-collective/leva.cljs
  {:git/sha "bb24493c8b4a0fcd862d69b4960fa297561fa5bb"}}
```

I checked it on the initial commit of your repro and it seems to do the job.

**Comment by matthewdowney** [comment]
Yes this works great, thank you!
